name: Go CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  secret-scan:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --only-verified

  build-and-tests:
    name: Build and Tests
    needs: secret-scan
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.26.1'
      - name: Sync Dependencies
        run: go mod tidy

      - name: Test with Coverage
        run: |
          go test -v -coverprofile=coverage.out ./tests/unitTests/...
          
          # Extrai o percentual total (ex: 74.5)
          TOTAL_COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "Cobertura total: $TOTAL_COVERAGE%"
          
          # Validação matemática (falha se for menor que 65.0)
          if (( $(echo "$TOTAL_COVERAGE < 65.0" | bc -l) )); then
            echo "❌ Erro: Cobertura de testes ($TOTAL_COVERAGE%) está abaixo da meta (65%)!"
            exit 1
          else
            echo "✅ Cobertura ($TOTAL_COVERAGE%) acima ou igual à meta!"
          fi